export enum SystemPath {
  index = 'system/index',
  task_index = 'system/task/index',
  task_shop = 'system/task/shop',
  task_gps = 'system/task/gps-task',
  task_file = 'system/task/shop/file',
  module = 'system/module',
  module_shop = 'system/module/shop',
  module_shop_registration = 'system/module/shop-registration',
  module_shop_compare = 'system/module/shop-compare',
  module_road = 'system/module/road',
  module_road_section = 'system/module/road-section',
  module_road_object = 'system/module/road-object',
  module_gps_task = 'system/module/gps-task',
  module_mobile_device_route = 'system/module/mobile-device-route',
  map = 'system/map',
  event = 'system/event',
  event_index = 'system/event/index',
  event_shop_manager = 'system/event/manager/shop',
  event_realtime_manager = 'system/event/manager/realtime',
  event_analysis_manager = 'system/event/manager/analysis',
  event_gps_task_manager = 'system/event/manager/gps-task',
}
