export enum SystemPath {
  index = 'system/index',
  task = 'system/task',
  task_file = 'system/task/file',
  module = 'system/module',
  module_shop = 'system/module/shop',
  module_shop_registration = 'system/module/shop-registration',
  module_shop_compare = 'system/module/shop-compare',
  module_road = 'system/module/road',
  map = 'system/map',
  event = 'system/event',
  event_index = 'system/event/index',
  event_shop_manager = 'system/event/manager/shop',
  event_realtime_manager = 'system/event/manager/realtime',
  event_analysis_manager = 'system/event/manager/analysis',
}
